### ISSUE TITLE
Design Assets

### ISSUE THREAD

**Issue by rknightuk** [danharper/T.R.U.M.P.#1]
- [ ] Citizen Man (for map and larger for video)
- [ ] Trump (happy and sad)
- [ ] Wall (Multiple images, losing bricks each time)
- [x] Back of people (for crowd for rally)
- [ ] pulsing dot for events

**Comment by alismith-dev** [comment]
I guess this is done then

**Comment by rknightuk** [comment]
¯_(ツ)_/¯
